name: Deployment of current GitHub repo on a server through SSH
on:
  push:
    branches: [main, develop]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: Rxinui/ssh-deploy-repo-action@v1
        with:
          # Required
          ssh-user: root
          ssh-password: ${{ secrets.iimActions }}
          ssh-domain: ${{ secrets.iimActionsDomaine }}
          known-hosts: ${{ secrets.hostkeys }}
          # Optional
          git-clone-by: ssh
          target-branch: main
          target-directory: /var/www/html/pgrimaud/