name: Deployment of current GitHub repo on a server through SSH
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: Rxinui/ssh-deploy-repo-action@v1
        with:
          # Required
          ssh-user: ${{ secrets.USER }}
          ssh-password: ${{ secrets.PASSWORD }}
          ssh-domain: ${{ secrets.DOMAINE }}
          # Optional
          git-clone-by: https
          target-branch: main
          target-directory: /var/www/html/adrien24/